version: '3'
services:
  elk-metricbeat:
    image:  docker.elastic.co/beats/metricbeat:5.4.0
    ports:
     - "9200:9200"
    environment:
     - xpack.security.enabled=false
    volumes:
     - ./:/usr/share/metricbeat/
     - /proc:/hostfs/proc:ro
     - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
     - /:/hostfs:ro
    network_mode: "host"
    command: ["metricbeat.config.modules.path:/usr/share/metricbeat/*.yaml", "metricbeat.config.modules.reload.period:10s", "metricbeat.config.modules.reload.enabled:true", "system.hostfs=/hostfs", "output.elasticsearch.hosts:[\"localhost:9200\"]"]  