version: '3'
services:
  elk-metricbeat:
    image:  docker.elastic.co/beats/metricbeat:5.4.0
    ports:
     - "9200:9200"
    environment:
     - xpack.security.enabled=false
     - ELASTICSEARCH_URL=http://localhost:9200
    volumes:
     - ./conf/metricbeat:/usr/share/metricbeat/confOriginal
     - /proc:/hostfs/proc:ro
     - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
     - /:/hostfs:ro
    network_mode: "host"